### ISSUE TITLE
Add support for Elgato Light Strip

### ISSUE THREAD

**Issue by sindrebroch** [frenck/python-elgato#279]
Thank you for a great library and component in HA.

### Subject of the feature

Add support for [Elgato Light Strip.](https://www.elgato.com/en/light-strip)

### Problem

I got my hands on an Elgato Light Strip, and found that this library can be used to control that as well, with a few small tweaks: 
It uses hue and saturation instead of temperature. 

I'm wondering if it's best to add these fields to the library, or to create a new library for each specific lighting device. 
There are a lot of comments specifying Elgato Key Light, should all these be updated to include light strip?

The same question also goes for component in HA, is it best to make the component more generic and include all devices? 

Hoping for a few tips on where to start adding support.

Thanks

**Comment by frenck** [comment]
I think the only thing needed it to provide a sort of "type" indication and add some arguments to allow for color communication.

Other than that... 🤷 

Nevertheless, I hope to receive mine today actually (well... it should have been here already, so I guess it will be tomorrow 😢 )

**Comment by sindrebroch** [comment]
Cool, thanks! 

I'll tinker around a bit and see if I can figure it out. I'm new to python, so it takes some time :)

**Comment by frenck** [comment]
@sindrebroch Spare yourself the time :) I've got it done already, writing the tests and will next update Home Assistant.

**Comment by sindrebroch** [comment]
Awesome! Looking forward to trying it :)
