### ISSUE TITLE
My Key Light does not have display name

### ISSUE THREAD

**Issue by dekoza** [frenck/python-elgato#394]
# Problem/Motivation

> My Elgato Key Light does not have a display name and this causes Info to break. I also get exception trying to set the display name.

## Expected behavior

> Display name should be ignored and not settable on some devices.

## Output of `accessory-info` endpoint

```
{"productName":"Elgato Key Light","hardwareBoardType":53,"firmwareBuildNumber":185,"firmwareVersion":"1.0.3","serialNumber":"CN12I1A03490","features":["lights"]}
```

What is the intended behavior in such case? I can provide a PR.

**Comment by frenck** [comment]
Thanks! I'm pushing out a fix for this in the next release. I've made it fallback to a default "Elgato Light".
